apiVersion: apps/v1
kind: Deployment
metadata:
  name: volvo-platform-app-deployment
  namespace: volvo
  labels:
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: volvo-image
          image: 471112730019.dkr.ecr.us-east-1.amazonaws.com/priv-volvo-platform-app:latest
          ports:
            - containerPort: 80
