apiVersion: apps/v1
kind: Deployment
metadata:
  name: volvo-platform-app-deployment
  labels:
    env: volvo-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      env: volvo-dev
  template:
    metadata:
      labels:
        env: volvo-dev
    spec:
      containers:
        - name: volvo-image
          image: public.ecr.aws/r0f6g4e3/volvo-platform-app:latest
          ports:
            - containerPort: 80
