name: Deploy Volvo to AWS EKS Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          config: ${{ secrets.KUBECONFIG }}

      - name: Configure kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: "latest"
          install-missing-components: true

      - name: Build Docker image
        run: |
          # aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/r0f6g4e3
          # docker build -t public.ecr.aws/r0f6g4e3/volvo-platform-app/volvo-image:latest ./volvo-platform-app
          # docker push public.ecr.aws/r0f6g4e3/volvo-platform-app/volvo-image:latest

          # aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/r0f6g4e3
          # docker build -t volvo-platform-app ./volvo-platform-app
          # docker tag volvo-platform-app:latest public.ecr.aws/r0f6g4e3/volvo-platform-app:latest
          # docker push public.ecr.aws/r0f6g4e3/volvo-platform-app:latest

      - name: Deploy to Kubernetes
        run: |
          echo $config > $HOME/.kube/config
          cat $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          kubectl get nodes
          echo $KUBECONFIG
          kubectl apply -f ./volvo-platform-app/volvo-app-deployment.yaml
