name: Deploy Volvo to AWS EKS Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build Docker image
        run: |
          docker build -t 471112730019.dkr.ecr.us-east-1.amazonaws.com/volvo-platform-app/volvo-image:latest ./volvo-platform-app
          docker push 471112730019.dkr.ecr.us-east-1.amazonaws.com/volvo-platform-app/volvo-image:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./volvo-platform-app/volvo-app-deployment.yaml
